# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FilePathField(max_length=255, path='/home/user/Projects/django_project/static/shop/images'),
        ),
    ]
