# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:42
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160730_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
