# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160801_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=255, upload_to='photos/'),
        ),
    ]
