# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20160816_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Orders', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='sum',
            field=models.FloatField(verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(through='shop.OrderProducts', to='shop.Products', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_sum',
            field=models.FloatField(verbose_name='Total sum'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.MyUsers', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categories', verbose_name='Category'),
        ),
    ]
